The7GATESArchive/Controllers/GatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace The7GATESArchive.Controllers
{
    public class GatesController : Controller
    {
        // GET: Gates
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Gate1()
        {
            return View();
        }
        public ActionResult Gate2()
        {
            return View();
        }
        public ActionResult Gate3()
        {
            return View();
        }
        public ActionResult Gate4()
        {
            return View();
        }
        public ActionResult Gate5()
        {
            return View();
        }
        public ActionResult Gate6()
        {
            return View();
        }
        public ActionResult Gate7()
        {
            return View();
        }
        public ActionResult BetaGate1()
        {
            return View();
        }
        public ActionResult BetaGate2()
        {
            return View();
        }
        public ActionResult BetaGate3()
        {
            return View();
        }


    }
}

The7GATESArchive/Views/Gates/BetaGate1.cshtml
<style>
    .gate1 {
        background-color: #e6335a;
        color: white;
        text-align: center;
        border: 2px solid #e6335a;
        border-radius: 8px;
    }

    .gate2 {
        background-color: #3fba84;
        color: white;
        text-align: center;
        border: 2px solid #3fba84;
        border-radius: 8px;
    }

    .gate3 {
        background-color: #34a9f6;
        color: white;
        text-align: center;
        border: 2px solid #34a9f6;
        border-radius: 8px;
    }

    .gate4 {
        background-color: #fe7b51;
        color: white;
        text-align: center;
        border: 2px solid #fe7b51;
        border-radius: 8px;
    }

    .gate5 {
        background-color: #f0be37;
        color: white;
        text-align: center;
        border: 2px solid #f0be37;
        border-radius: 8px;
    }

    .gate6 {
        background-color: #a74cc1;
        color: white;
        text-align: center;
        border: 2px solid #a74cc1;
        border-radius: 8px;
    }

    .gate7 {
        background-color: #282828;
        color: white;
        text-align: center;
        border: 2px solid #282828;
        border-radius: 8px;
    }
    .bg1 {
        background-color: #000000;
        color: white;
        text-align: center;
        border: 2px solid #e6335a;
        border-radius: 8px;
    }
    .bg2 {
        background-color: #000000;
        color: white;
        text-align: center;
        border: 2px solid #282828;
        border-radius: 8px;
    }
    .bg3 {
        background-color: #000000;
        color: white;
        text-align: center;
        border: 2px solid #282828;
        border-radius: 8px;
    }

    .g1button {
        color: #e6335a;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #e6335a;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g2button {
        color: #3fba84;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #3fba84;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g3button {
        color: #34a9f6;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #34a9f6;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g4button {
        color: #fe7b51;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #fe7b51;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g5button {
        color: #f0be37;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #f0be37;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g6button {
        color: #a74cc1;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #a74cc1;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g7button {
        color: #282828;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #282828;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }
</style>
<h4></h4>
<div class="bg1" style="background-color:#e6335a">
    <h1 class="gate1"><strong>BETA GATE 1</strong></h1>
    <img src="~/Assets/BetaGate1Open.gif" alt="Beta Gate 1" height="128px" width="128px" />
    <img src="~/Assets/BetaGate1.gif" alt="Beta Gate 1" height="128px" width="128px" style="border-radius:65px"/>
    <h3></h3>

    <div class="gate1">
        <h2 id="demo" style="font-size:40px;padding-bottom:10px"></h2>
    </div>
    <br />
    <script>
        // Set the date we're counting down to
        var myDateObj = new Date("Fri Dec 21 2018 04:00:00 GMT-0000 (UTC)");
        myDateObj.toString();

        // Update the count down every 1 second
        var x = setInterval(function () {

            // Get todays date and time
            var now = new Date().getTime();

            // Find the distance between now and the count down date
            var distance = myDateObj - now;

            // Time calculations for days, hours, minutes and seconds
            var days = Math.floor(distance / (1000 * 60 * 60 * 24));
            var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((distance % (1000 * 60)) / 1000);

            // Output the result in an element with id="demo"
            document.getElementById("demo").innerHTML = days + ":" + hours + ":"
                + minutes + ":" + seconds;

            // If the count down is over, write some text
            if (distance < 0) {
                clearInterval(x);
                document.getElementById("demo").innerHTML = "GO GO GO! COMPLETE THAT GATE!";
            }
        }, 1000);
    </script>
</div>
<br />
<div class="bg1" style="border:2px solid #282828">
    <h4></h4>
    <h3>THEME: GAME THEORY ARG</h3>
    <h3>OPENS/ED ON: Dec 20th, 2018 8:00PM PST</h3>
    <h3>NUMBER OF KEYS: 3</h3>
    <h3>AMOUNT COMPLETED: DATA UNAVAILABLE</h3>
    <h3 color="red">Help Out CreatorINK With Bug Fixing!</h3>
    <h3>@Html.ActionLink("<<< Back to List", "Index", "Gates")</h3>
    <h3></h3>
</div>
<h4></h4>

The7GATESArchive/Views/Gates/BetaGate2.cshtml
<style>
    .gate1 {
        background-color: #e6335a;
        color: white;
        text-align: center;
        border: 2px solid #e6335a;
        border-radius: 8px;
    }

    .gate2 {
        background-color: #3fba84;
        color: white;
        text-align: center;
        border: 2px solid #3fba84;
        border-radius: 8px;
    }

    .gate3 {
        background-color: #34a9f6;
        color: white;
        text-align: center;
        border: 2px solid #34a9f6;
        border-radius: 8px;
    }

    .gate4 {
        background-color: #fe7b51;
        color: white;
        text-align: center;
        border: 2px solid #fe7b51;
        border-radius: 8px;
    }

    .gate5 {
        background-color: #f0be37;
        color: white;
        text-align: center;
        border: 2px solid #f0be37;
        border-radius: 8px;
    }

    .gate6 {
        background-color: #a74cc1;
        color: white;
        text-align: center;
        border: 2px solid #a74cc1;
        border-radius: 8px;
    }

    .gate7 {
        background-color: #282828;
        color: white;
        text-align: center;
        border: 2px solid #282828;
        border-radius: 8px;
    }

    .bg1 {
        background-color: #000000;
        color: white;
        text-align: center;
        border: 2px solid #e6335a;
        border-radius: 8px;
    }

    .bg2 {
        background-color: #000000;
        color: white;
        text-align: center;
        border: 2px solid #282828;
        border-radius: 8px;
    }

    .bg3 {
        background-color: #000000;
        color: white;
        text-align: center;
        border: 2px solid #282828;
        border-radius: 8px;
    }

    .g1button {
        color: #e6335a;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #e6335a;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g2button {
        color: #3fba84;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #3fba84;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g3button {
        color: #34a9f6;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #34a9f6;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g4button {
        color: #fe7b51;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #fe7b51;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g5button {
        color: #f0be37;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #f0be37;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g6button {
        color: #a74cc1;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #a74cc1;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g7button {
        color: #282828;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #282828;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }
</style>
<h4></h4>
<div class="bg2" style="background-color:#3fba84">
    <h1 class="gate2"><strong>BETA GATE 2</strong></h1>
    <img src="~/Assets/BetaGate2Official.gif" alt="Beta Gate 1" height="128px" width="128px" />
    <img src="~/Assets/BetaGate2.gif" alt="Beta Gate 2" height="128px" width="128px" style="border-radius:65px" />
    <h3></h3>

    <div class="gate2">
        <h2 id="demo" style="font-size:40px;padding-bottom:10px"></h2>
    </div>
    <br />
    <script>
        // Set the date we're counting down to
        var myDateObj = new Date("Sat Dec 29 2018 04:00:00 GMT-0000 (UTC)");
        myDateObj.toString();

        // Update the count down every 1 second
        var x = setInterval(function () {

            // Get todays date and time
            var now = new Date().getTime();

            // Find the distance between now and the count down date
            var distance = myDateObj - now;

            // Time calculations for days, hours, minutes and seconds
            var days = Math.floor(distance / (1000 * 60 * 60 * 24));
            var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((distance % (1000 * 60)) / 1000);

            // Output the result in an element with id="demo"
            document.getElementById("demo").innerHTML = days + ":" + hours + ":"
                + minutes + ":" + seconds;

            // If the count down is over, write some text
            if (distance < 0) {
                clearInterval(x);
                document.getElementById("demo").innerHTML = "GO GO GO! COMPLETE THAT GATE!";
            }
        }, 1000);
    </script>
</div>
<br />
<div class="bg1" style="border:2px solid #282828">
    <h4></h4>
    <h3>THEME: GAME THEORY ARG</h3>
    <h3>OPENS/ED ON: Dec 20th, 2018 8:00PM PST</h3>
    <h3>NUMBER OF KEYS: 3</h3>
    <h3>AMOUNT COMPLETED: DATA UNAVAILABLE</h3>
    <h3 color="red">Help Out CreatorINK With Bug Fixing!</h3>
    <h3>@Html.ActionLink("<<< Back to List", "Index", "Gates")</h3>
    <h3></h3>
</div>
<h4></h4>

The7GATESArchive/Views/Gates/BetaGate3.cshtml
<style>
    .gate1 {
        background-color: #e6335a;
        color: white;
        text-align: center;
        border: 2px solid #e6335a;
        border-radius: 8px;
    }

    .gate2 {
        background-color: #3fba84;
        color: white;
        text-align: center;
        border: 2px solid #3fba84;
        border-radius: 8px;
    }

    .gate3 {
        background-color: #34a9f6;
        color: white;
        text-align: center;
        border: 2px solid #34a9f6;
        border-radius: 8px;
    }

    .gate4 {
        background-color: #fe7b51;
        color: white;
        text-align: center;
        border: 2px solid #fe7b51;
        border-radius: 8px;
    }

    .gate5 {
        background-color: #f0be37;
        color: white;
        text-align: center;
        border: 2px solid #f0be37;
        border-radius: 8px;
    }

    .gate6 {
        background-color: #a74cc1;
        color: white;
        text-align: center;
        border: 2px solid #a74cc1;
        border-radius: 8px;
    }

    .gate7 {
        background-color: #282828;
        color: white;
        text-align: center;
        border: 2px solid #282828;
        border-radius: 8px;
    }

    .bg1 {
        background-color: #000000;
        color: white;
        text-align: center;
        border: 2px solid #e6335a;
        border-radius: 8px;
    }

    .bg2 {
        background-color: #000000;
        color: white;
        text-align: center;
        border: 2px solid #282828;
        border-radius: 8px;
    }

    .bg3 {
        background-color: #000000;
        color: white;
        text-align: center;
        border: 2px solid #282828;
        border-radius: 8px;
    }

    .g1button {
        color: #e6335a;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #e6335a;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g2button {
        color: #3fba84;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #3fba84;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g3button {
        color: #34a9f6;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #34a9f6;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g4button {
        color: #fe7b51;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #fe7b51;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g5button {
        color: #f0be37;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #f0be37;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g6button {
        color: #a74cc1;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #a74cc1;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g7button {
        color: #282828;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #282828;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }
</style>
<h4></h4>
<div class="bg3" style="background-color:#34a9f6">
    <h1 class="gate3"><strong>BETA GATE 3</strong></h1>
    <img src="~/Assets/BetaGate3Official.png" alt="Beta Gate 1" height="128px" width="128px" />
    <img src="~/Assets/BetaGate3.png" alt="Beta Gate 3" height="128px" width="128px" style="border-radius:65px" />
    <h3></h3>

    <div class="gate3">
        <!--<h2 id="demo" style="font-size:40px;padding-bottom:10px"></h2>-->
        <h2>Not Yet Released</h2>
    </div>
    <br />
    <script>
        // Set the date we're counting down to
        var myDateObj = new Date("Fri Dec 21 2018 04:00:00 GMT-0000 (UTC)");
        myDateObj.toString();

        // Update the count down every 1 second
        var x = setInterval(function () {

            // Get todays date and time
            var now = new Date().getTime();

            // Find the distance between now and the count down date
            var distance = myDateObj - now;

            // Time calculations for days, hours, minutes and seconds
            var days = Math.floor(distance / (1000 * 60 * 60 * 24));
            var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((distance % (1000 * 60)) / 1000);

            // Output the result in an element with id="demo"
            document.getElementById("demo").innerHTML = days + ":" + hours + ":"
                + minutes + ":" + seconds;

            // If the count down is over, write some text
            if (distance < 0) {
                clearInterval(x);
                document.getElementById("demo").innerHTML = "GO GO GO! COMPLETE THAT GATE!";
            }
        }, 1000);
    </script>
</div>
<br />
<div class="bg1" style="border:2px solid #282828">
    <h4></h4>
    <h3>THEME: GAME THEORY ARG</h3>
    <h3>OPENS/ED ON: JANUARY 12th, 2018 (8:00PM PST)</h3>
    <h3>NUMBER OF KEYS: 2</h3>
    <h3>AMOUNT COMPLETED: AWAITING DATA</h3>
    <h3 color="red">Help Out CreatorINK With Bug Fixing!</h3>
    <h3>@Html.ActionLink("<<< Back to List", "Index", "Gates")</h3>
    <h3></h3>
</div>
<h4></h4>

The7GATESArchive/Views/Gates/Gate1.cshtml
<style>
    * {
        background: rgb(200,101,0);
        background: linear-gradient(90deg, rgba(200,101,0,1) 0%, rgba(233,125,2,1) 40%, rgba(255,111,0,1) 56%, rgba(255,135,0,1) 86%, rgba(255,175,77,1) 100%);
    }
</style>
<h4></h4>
<div class="gate1">
    <h1 class="gate1"><strong>GATE 1</strong></h1>

    <img src="~/Assets/gate1.gif" alt="Gate 1 Image" height="128px" width="128px" />
    <img src="~/Assets/Gate1Logo.gif" alt="Gate 1 Logo" height="128px" width="128px" style="border-radius:65px" />
    <h3></h3>
    <div class="gate1">
        <h2 id="demo" style="font-size:40px;padding-bottom:10px"></h2>
    </div>
    <br />
    <script>
        // Set the date we're counting down to
        var myDateObj = new Date("Sat Nov 24 2018 16:00:00 GMT-0000 (UTC)");
        myDateObj.toString();

        // Update the count down every 1 second
        var x = setInterval(function () {

            // Get todays date and time
            var now = new Date().getTime();

            // Find the distance between now and the count down date
            var distance = myDateObj - now;

            // Time calculations for days, hours, minutes and seconds
            var days = Math.floor(distance / (1000 * 60 * 60 * 24));
            var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((distance % (1000 * 60)) / 1000);

            // Output the result in an element with id="demo"
            document.getElementById("demo").innerHTML = days + ":" + hours + ":"
                + minutes + ":" + seconds;

            // If the count down is over, write some text
            if (distance < 0) {
                clearInterval(x);
                document.getElementById("demo").innerHTML = "GO GO GO! COMPLETE THAT GATE!";
            }
        }, 1000);
    </script>
</div>
<h4></h4>
<div class="gate1" style="background-color:#000000;border:2px solid #e04e6e">
    <h4></h4>
    <h3>THEME: NINTENDO</h3>
    <h3>OPENS/ED ON: NOVEMBER 24th, 2018 (12:07PM PST)</h3>
    <h3>NUMBER OF KEYS: 5</h3>
    <h3>AMOUNT COMPLETED: ABOUT 30,000</h3>
    <h3>@Html.ActionLink("<<< Back to List", "Index", "Gates")</h3>
    <h3></h3>
</div>
<h4></h4>
<div class="gate1" style="background-color:#e04e6e;border:2px solid #e04e6e;float:right;border-radius:4px">@Html.ActionLink("Gate 2 >>>", "Gate2", "Gates")</div>

The7GATESArchive/Views/Gates/Gate2.cshtml
<style>
    .gate1 {
        background-color: #e6335a;
        color: white;
        text-align: center;
        border: 2px solid #e6335a;
        border-radius: 8px;
    }

    .gate2 {
        background-color: #3fba84;
        color: white;
        text-align: center;
        border: 2px solid #3fba84;
        border-radius: 8px;
    }

    .gate3 {
        background-color: #34a9f6;
        color: white;
        text-align: center;
        border: 2px solid #34a9f6;
        border-radius: 8px;
    }

    .gate4 {
        background-color: #fe7b51;
        color: white;
        text-align: center;
        border: 2px solid #fe7b51;
        border-radius: 8px;
    }

    .gate5 {
        background-color: #f0be37;
        color: white;
        text-align: center;
        border: 2px solid #f0be37;
        border-radius: 8px;
    }

    .gate6 {
        background-color: #a74cc1;
        color: white;
        text-align: center;
        border: 2px solid #a74cc1;
        border-radius: 8px;
    }

    .gate7 {
        background-color: #282828;
        color: white;
        text-align: center;
        border: 2px solid #282828;
        border-radius: 8px;
    }

    .g1button {
        color: #e6335a;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #e6335a;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g2button {
        color: #3fba84;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #3fba84;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g3button {
        color: #34a9f6;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #34a9f6;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g4button {
        color: #fe7b51;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #fe7b51;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g5button {
        color: #f0be37;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #f0be37;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g6button {
        color: #a74cc1;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #a74cc1;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }

    .g7button {
        color: #282828;
        background-color: lightgray;
        text-align: center;
        border: 4px solid #282828;
        font-family: Courier New, Courier, monospace;
        border-radius: 4px;
        font-size: 20px;
    }
</style>
<h4></h4>
<div class="gate2">
    <h1 class="gate2"><strong>GATE 2</strong></h1>

    <img src="~/Assets/gate2.png" alt="Gate 2 Image" height="128px" width="128px" />
    <img src="~/Assets/Gate2Logo.png" alt="Gate 2 Logo" height="128px" width="128px" style="border-radius:65px" />
    <h3></h3>
    <div class="gate2">
        <!--<h2 id="demo" style="font-size:40px;padding-bottom:10px"></h2>-->
        <h2>Not Yet Released!</h2>
    </div>
    <br />
    <script>
        // Set the date we're counting down to
        var myDateObj = new Date("Sat Dec 21 2018 04:00:00 GMT-0000 (UTC)");
        myDateObj.toString();

        // Update the count down every 1 second
        var x = setInterval(function () {

            // Get todays date and time
            var now = new Date().getTime();

            // Find the distance between now and the count down date
            var distance = myDateObj - now;

            // Time calculations for days, hours, minutes and seconds
            var days = Math.floor(distance / (1000 * 60 * 60 * 24));
            var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((distance % (1000 * 60)) / 1000);

            // Output the result in an element with id="demo"
            document.getElementById("demo").innerHTML = days + ":" + hours + ":"
                + minutes + ":" + seconds;

            // If the count down is over, write some text
            if (distance < 0) {
                clearInterval(x);
                document.getElementById("demo").innerHTML = "GO GO GO! COMPLETE THAT GATE!";
            }
        }, 1000);
    </script>
</div>
<h4></h4>
<div class="gate2" style="background-color:#000000;border:2px solid #3fba84">
    <h2><strong>>>> OPEN <<<</strong></h2>
    <h4></h4>
    <h3>THEME: INDIE GAMES</h3>
    <h3>OPENS/ED ON: JANUARY 19th, 2019 (2:22PM PST) [DELAYED FROM DECEMBER]</h3>
    <h3>NUMBER OF KEYS: 4</h3>
    <h3>AMOUNT COMPLETED: AWAITING DATA</h3>
    <h3>@Html.ActionLink("<<< Back to List", "Index", "Gates")</h3>
    <h3></h3>
</div>
<h4></h4>
<div class="gate2" style="float:right;border-radius:4px">@Html.ActionLink("Gate 3 >>>", "Gate3", "Gates")</div>
<div class="gate2" style="float:left;border-radius:4px">@Html.ActionLink("<<< Gate 1", "Gate1", "Gates")</div>